version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
    #- echo Entered Install phase...
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - ls -la
artifacts:
  files:
    - appspec.yml
    - scripts/afterInstall.sh
  base_directory: build
  files:
    - '**/*'
