AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Upload course image function
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'POST'"
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-Type'"

Resources:
  UploadImageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      FunctionName: upload-course-image-function
      Environment:
        Variables:
          BUCKET_NAME: mylms-frontend-app
      Role: arn:aws:iam::397178420157:role/Lambda_S3
      Events:
        UploadImageApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploadImageApiApi:
    Description: "API Gateway endpoint URL for Prod stage for upload course image function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"
  UploadImageFunction:
    Description: "Upload course image Lambda Function ARN"
    Value: !GetAtt UploadImageFunction.Arn