AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to create API that triggers a Lambda function to get all students.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  FetchStudentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fetch/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      FunctionName: fetch-students-function
      Role: 'arn:aws:iam::397178420157:role/lambda-dynamo-role'
      # Declare a policy to be able to read/add table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StudentsDynamoDBTable
      Environment:
        Variables:
          DDB_TABLE: !Ref StudentsDynamoDBTable
      Events:
        FetchStudentsFunctionApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /students/{proxy+}
            Method: get

  StudentsDynamoDBTable:
    Type: "AWS::Serverless::SimpleTable"
    Properties:
      TableName: StudentsTable

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FetchStudentsFunctionApi:
    Description: "API Gateway endpoint URL for FetchStudentsFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Fetch students Lambda Function ARN"
    Value: !GetAtt FetchStudentsFunction.Arn