/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:7409f69b-523b-4290-aa64-050158d26b57",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_y782biQ5y",
    "aws_user_pools_web_client_id": "5vijn2bii7nvk0edqqt16464l3",
    "oauth": {}
};


export default awsmobile;
